-- Demo bookings for Apollo Care (idempotent, superuser bypasses RLS).
-- Creates today's slots + bookings (mixed statuses) referencing seeded doctors+patients.
-- booking_number is filled by trg_booking_number. Run after seed_demo_doctors + _patients.
\set tenant_id '11111111-1111-1111-1111-111111111111'

-- Today's slots (one per booking, status 'booked').
INSERT INTO docslot.time_slots (slot_id, tenant_id, doctor_id, slot_date, start_time, end_time, status, max_count, current_count)
SELECT md5('apollo-slot-'||ph||doc)::uuid, :'tenant_id', md5('apollo-doc-'||doc)::uuid,
       CURRENT_DATE, st::time, et::time, 'booked', 1, 1
FROM (VALUES
  ('+919820000072','Dr. Anjali Sharma','11:30','11:45'),
  ('+919820000012','Dr. Rohan Iyer','12:00','12:15'),
  ('+919820000034','Dr. Priya Nair','10:45','11:00'),
  ('+919820000032','Dr. Meera Krishnan','10:30','10:45'),
  ('+919820000020','Dr. Vikram Bose','13:15','13:30'),
  ('+919820000089','Dr. Saurabh Gupta','14:00','14:15'),
  ('+919820000011','Dr. Lakshmi Rao','10:15','10:30'),
  ('+919820000081','Dr. Priya Nair','09:45','10:00'),
  ('+919820000014','Dr. Faisal Khan','15:00','15:15'),
  ('+919820000023','Dr. Lakshmi Rao','09:30','09:45')
) AS s(ph,doc,st,et)
ON CONFLICT (slot_id) DO NOTHING;

-- Bookings (booking_number auto-generated by trigger).
INSERT INTO docslot.bookings
    (booking_id, tenant_id, slot_id, patient_id, doctor_id, department_id, status, booked_via, notes, booked_at, confirmed_at, no_show_at)
SELECT md5('apollo-bk-'||ph||doc)::uuid, :'tenant_id',
       md5('apollo-slot-'||ph||doc)::uuid, md5('apollo-pat-'||ph)::uuid, md5('apollo-doc-'||doc)::uuid,
       md5('apollo-dept-'||dept)::uuid, status, via, note, NOW(),
       CASE WHEN status='confirmed' THEN NOW() END,
       CASE WHEN status='no_show' THEN NOW() END
FROM (VALUES
  ('+919820000072','Dr. Anjali Sharma','Cardiology','pending','whatsapp','Chest pain since morning'),
  ('+919820000012','Dr. Rohan Iyer','Cardiology','pending','whatsapp','Follow-up — ECG report attached'),
  ('+919820000034','Dr. Priya Nair','Gynaecology','pending','whatsapp','First visit — antenatal'),
  ('+919820000081','Dr. Priya Nair','Gynaecology','pending','walk_in','Routine check'),
  ('+919820000032','Dr. Meera Krishnan','Paediatrics','confirmed','whatsapp','Fever 102°F, cough'),
  ('+919820000020','Dr. Vikram Bose','Orthopedics','confirmed','walk_in','Knee pain — review'),
  ('+919820000089','Dr. Saurabh Gupta','Dermatology','confirmed','whatsapp','Rash on forearms'),
  ('+919820000011','Dr. Lakshmi Rao','General Medicine','completed','phone_call','BP review'),
  ('+919820000023','Dr. Lakshmi Rao','General Medicine','completed','whatsapp','Routine checkup'),
  ('+919820000014','Dr. Faisal Khan','ENT','no_show','whatsapp','Throat infection')
) AS b(ph,doc,dept,status,via,note)
ON CONFLICT (booking_id) DO NOTHING;

SELECT status, count(*) FROM docslot.bookings WHERE tenant_id = :'tenant_id' GROUP BY status ORDER BY status;
