using mediq.SharedDataModel.Docslot.Dashboard.Enums;

namespace mediq.SharedDataModel.Docslot.Dashboard.Dtos;

/// <summary>
/// Read-model for one row in the reception-desk approval queue / booking list.
/// <para>
/// Composed from <c>docslot.bookings</c> joined to <c>docslot.patients</c>,
/// <c>docslot.doctors</c>, <c>docslot.departments</c>, and <c>docslot.time_slots</c>
/// (database/03_docslot.sql). Read-only projection — not an EF entity.
/// </para>
/// <para>
/// PHI / compliance: the patient's full phone number is PHI under DPDP. This list DTO
/// exposes ONLY <see cref="MaskedPhone"/>; the unmasked number is never serialized into
/// the queue. Revealing the full number is a separate, purpose-of-use-gated patient read
/// (see <see cref="DashboardContract"/>). The list intentionally prefers the booking-time
/// snapshot fields (<c>patient_name_at_booking</c>, <c>patient_age_at_booking</c>) so the
/// row reflects what was true when booked.
/// </para>
/// </summary>
/// <param name="BookingId">PK. Maps to <c>bookings.booking_id</c> (UUID).</param>
/// <param name="BookingNumber">
/// Human-readable code <c>BKG-YYYY-MM-NNNNN</c> (e.g. <c>BKG-2026-04-00001</c>).
/// Maps to <c>bookings.booking_number</c> (generated by trigger <c>trg_booking_number</c>).
/// </param>
/// <param name="TokenNumber">
/// OPD queue token number, when the booking has one. Maps to
/// <c>docslot.opd_tokens.token_number</c> (INT) for the booking; null if no token issued.
/// </param>
/// <param name="PatientDisplayName">
/// Patient display name. Prefers the snapshot <c>bookings.patient_name_at_booking</c>,
/// falling back to <c>patients.full_name</c>. Nullable because both may be null.
/// </param>
/// <param name="MaskedPhone">
/// Masked phone for the desk (e.g. <c>+91 98xxxx xx10</c>). Derived from
/// <c>bookings.patient_phone_at_booking</c> / <c>patients.phone_number</c> by the API's
/// masking helper — the raw value is NEVER placed here. PHI guard.
/// </param>
/// <param name="Age">
/// Patient age. Prefers snapshot <c>bookings.patient_age_at_booking</c>, falling back to
/// <c>patients.age</c> (SMALLINT). Nullable.
/// </param>
/// <param name="Gender">Patient gender. Maps to <c>patients.gender</c> (nullable CHECK enum).</param>
/// <param name="DoctorName">
/// Treating provider. Prefers <c>doctors.display_name</c>, falling back to
/// <c>doctors.full_name</c>.
/// </param>
/// <param name="DepartmentName">
/// Department label. Maps to <c>departments.name</c>; null when <c>department_id</c> is null
/// (department is optional on a booking).
/// </param>
/// <param name="SlotStart">
/// Slot start as an explicit instant. Composed from <c>time_slots.slot_date</c> +
/// <c>time_slots.start_time</c> and emitted as a <see cref="DateTimeOffset"/> carrying the
/// <b>Asia/Kolkata</b> (+05:30) offset (see <see cref="DashboardContract"/>). The DB stores
/// date + wall-clock TIME; the API attaches the IST offset.
/// </param>
/// <param name="SlotEnd">
/// Slot end, same composition/offset rules as <paramref name="SlotStart"/>
/// (<c>time_slots.end_time</c>).
/// </param>
/// <param name="Status">Lifecycle status. Maps to <c>bookings.status</c>.</param>
/// <param name="Source">Origin channel. Maps to <c>bookings.booked_via</c>.</param>
/// <param name="Note">
/// Free-text note for the desk. Maps to <c>bookings.notes</c>
/// (or <c>chief_complaint</c> when surfaced). Nullable.
/// </param>
/// <param name="CreatedAt">
/// When the booking was created, as a UTC-offset instant. Maps to <c>bookings.booked_at</c>
/// (TIMESTAMPTZ). The "x min ago" label is computed client-side from this — the API does not
/// ship a localized relative string.
/// </param>
/// <param name="Language">
/// Patient's preferred language for this interaction. Maps to
/// <c>patients.preferred_language</c> (nullable; free VARCHAR, see <see cref="Enums.Language"/>).
/// </param>
public sealed record BookingListItemDto(
    Guid BookingId,
    string BookingNumber,
    int? TokenNumber,
    string? PatientDisplayName,
    string MaskedPhone,
    int? Age,
    Gender? Gender,
    string? DoctorName,
    string? DepartmentName,
    DateTimeOffset SlotStart,
    DateTimeOffset SlotEnd,
    BookingStatus Status,
    BookingSource Source,
    string? Note,
    DateTimeOffset CreatedAt,
    Language? Language);
